---
version: '3.4'
x-tftpd:
  &default_tftpd
  build:
    context: .
  image: ghcr.io/acidsailor/tftpd:latest

services:
  tftpd_latest: *default_tftpd
  tftpd_version:
    <<: *default_tftpd
    image: ghcr.io/acidsailor/tftpd:v2.0
